api:
  github:
    users: https://api.github.com/users/%s
    followers: https://api.github.com/users/%s/followers
    repos: https://api.github.com/users/%s/repos

host:
  name: localhost

server:
  port: 8081
  comtextPath: /
  tomcat:
    access-log-enabled: true
    access-log-pattern: %a %{X-Forwarded-For}i %l %u %t &quot;%r&quot; %s %b

spring:
  applicaiton:
    name: rascal-api
  jpa:
    hibernate:
      ddl-auto: create-drop